----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
local cFunc = {}
local cSetting = {}


function removewpn(thePlayer,wpn)
    takeWeapon( thePlayer, wpn )
end
addEvent("removewpn",true)
addEventHandler ( "removewpn", getRootElement(), removewpn )
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

addEventHandler("onResourceStart", resourceRoot,
function()
------------------------------- PISTOL
        setWeaponProperty(22, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(22, "poor", "flag_move_and_aim", true)
        setWeaponProperty(22, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(22, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(22, "poor", "anim_loop_stop", 1.9)
        setWeaponProperty(22, "poor", "anim2_loop_stop", 1.9)
        setWeaponProperty(22, "poor", "accuracy", 300)
        setWeaponProperty(22, "std", "damage", 75)
        setWeaponProperty(22, "pro", "damage", 75)
        setWeaponProperty(22, "poor", "damage", 75)
        setWeaponProperty(22, "poor", "weapon_range", 40)
        setWeaponProperty(22, "std", "weapon_range", 40)
        setWeaponProperty(22, "pro", "weapon_range", 40)
------------------------------- WINCHESTER
        setWeaponProperty(33, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(33, "poor", "flag_move_and_aim", true)
        setWeaponProperty(33, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(33, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(33, "poor", "maximum_clip_ammo", 1)
        setWeaponProperty(33, "poor", "anim_loop_stop", 1.9)
        setWeaponProperty(33, "poor", "anim2_loop_stop", 1.9)
        setWeaponProperty(33, "poor", "accuracy", 300)
        setWeaponProperty(33, "std", "damage", 150)
        setWeaponProperty(33, "pro", "damage", 150)
        setWeaponProperty(33, "poor", "damage", 150)
        setWeaponProperty(33, "std", "weapon_range", 550)
        setWeaponProperty(33, "pro", "weapon_range", 550)
        setWeaponProperty(33, "poor", "weapon_range", 550)
------------------------------- GLOCK
        setWeaponProperty(24, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(24, "poor", "flag_move_and_aim", true)
        setWeaponProperty(24, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(24, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(24, "poor", "flag_anim_reload_long", false)
        setWeaponProperty(24, "std", "flag_move_and_shoot", true)
        setWeaponProperty(24, "std", "flag_move_and_aim", true)
        setWeaponProperty(24, "std", "flag_aim_1st_person", false)
        setWeaponProperty(24, "std", "flag_aim_no_auto", true)
        setWeaponProperty(24, "std", "flag_anim_reload_long", false)
        setWeaponProperty(24, "pro", "flag_move_and_shoot", true)
        setWeaponProperty(24, "pro", "flag_move_and_aim", true)
        setWeaponProperty(24, "pro", "flag_aim_1st_person", false)
        setWeaponProperty(24, "pro", "flag_aim_no_auto", true)
        setWeaponProperty(24, "pro", "flag_anim_reload_long", false)
        setWeaponProperty(24, "poor", "anim_loop_stop", 0.5)
        setWeaponProperty(24, "std", "anim_loop_stop", 0.5)
        setWeaponProperty(24, "pro", "anim_loop_stop", 0.5)
        setWeaponProperty(24, "poor", "anim2_loop_stop", 0.07)
        setWeaponProperty(24, "std", "anim2_loop_stop", 0.07)
        setWeaponProperty(24, "pro", "anim2_loop_stop", 0.07)
        setWeaponProperty(24, "std", "maximum_clip_ammo", 13)
        setWeaponProperty(24, "pro", "maximum_clip_ammo", 13)
        setWeaponProperty(24, "poor", "maximum_clip_ammo", 13)
        setWeaponProperty(24, "std", "accuracy",100)
        setWeaponProperty(24, "pro", "accuracy",100)
        setWeaponProperty(24, "poor", "accuracy", 100)
        setWeaponProperty(24, "poor", "weapon_range", 30)
        setWeaponProperty(24, "std", "weapon_range", 30)
        setWeaponProperty(24, "pro", "weapon_range", 30)
        setWeaponProperty(24, "std", "damage", 90)
        setWeaponProperty(24, "pro", "damage", 90)
        setWeaponProperty(24, "poor", "damage", 90)
------------------------------- TASER
        setWeaponProperty(23, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(23, "poor", "flag_move_and_aim", true)
        setWeaponProperty(23, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(23, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(23, "poor", "flag_anim_reload_long", false)
        setWeaponProperty(23, "std", "flag_move_and_shoot", true)
        setWeaponProperty(23, "std", "flag_move_and_aim", true)
        setWeaponProperty(23, "std", "flag_aim_1st_person", false)
        setWeaponProperty(23, "std", "flag_aim_no_auto", true)
        setWeaponProperty(23, "std", "flag_anim_reload_long", false)
        setWeaponProperty(23, "pro", "flag_move_and_shoot", true)
        setWeaponProperty(23, "pro", "flag_move_and_aim", true)
        setWeaponProperty(23, "pro", "flag_aim_1st_person", false)
        setWeaponProperty(23, "pro", "flag_aim_no_auto", true)
        setWeaponProperty(23, "pro", "flag_anim_reload_long", false)
        setWeaponProperty(23, "pro", "maximum_clip_ammo", 1)
        setWeaponProperty(23, "std", "maximum_clip_ammo", 1)
        setWeaponProperty(23, "poor", "maximum_clip_ammo", 1)
        setWeaponProperty(23, "poor", "accuracy", 20)
        setWeaponProperty(23, "poor", "weapon_range", 7)
        setWeaponProperty(23, "std", "weapon_range", 7)
        setWeaponProperty(23, "pro", "weapon_range", 7)
        setWeaponProperty(23, "std", "damage", 1)
        setWeaponProperty(23, "pro", "damage", 1)
        setWeaponProperty(23, "poor", "damage", 1)
        setWeaponProperty(23, "std", "anim2_loop_stop", 0.7)
        setWeaponProperty(23, "pro", "anim2_loop_stop", 0.7)
        setWeaponProperty(23, "poor", "anim2_loop_stop", 0.7)
        setWeaponProperty(23, "std", "anim_loop_stop", 0.9)
        setWeaponProperty(23, "pro", "anim_loop_stop", 0.9)
        setWeaponProperty(23, "poor", "anim_loop_stop", 0.9)
        setWeaponProperty(23, "std", "accuracy",20)
        setWeaponProperty(23, "pro", "accuracy",20)
------------------------------- M4A1
        setWeaponProperty(31, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(31, "poor", "flag_move_and_aim", true)
        setWeaponProperty(31, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(31, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(31, "poor", "flag_anim_reload_long", false)
        setWeaponProperty(31, "poor", "anim_loop_stop", 0.5)
        setWeaponProperty(31, "poor", "anim2_loop_stop", 0.07)
        setWeaponProperty(31, "poor", "maximum_clip_ammo", 13)
        setWeaponProperty(31, "pro", "accuracy", 300)
        setWeaponProperty(31, "std", "weapon_range", 550)
        setWeaponProperty(31, "pro", "weapon_range", 550)
        setWeaponProperty(31, "poor", "weapon_range", 550)
        setWeaponProperty(31, "std", "damage", 120)
        setWeaponProperty(31, "pro", "damage", 120)
        setWeaponProperty(31, "poor", "damage", 120)
------------------------------- AK-47
        setWeaponProperty(30, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(30, "poor", "flag_move_and_aim", true)
        setWeaponProperty(30, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(30, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(30, "poor", "flag_anim_reload_long", false)
        setWeaponProperty(30, "poor", "anim_loop_stop", 0.5)
        setWeaponProperty(30, "poor", "anim2_loop_stop", 0.07)
        setWeaponProperty(30, "poor", "maximum_clip_ammo", 13)
        setWeaponProperty(30, "pro", "accuracy", 300)
        setWeaponProperty(30, "std", "weapon_range", 550)
        setWeaponProperty(30, "pro", "weapon_range", 550)
        setWeaponProperty(30, "poor", "weapon_range", 550)
        setWeaponProperty(30, "std", "damage", 120)
        setWeaponProperty(30, "pro", "damage", 120)
        setWeaponProperty(30, "poor", "damage", 120)
------------------------------- Uzi
        setWeaponProperty(28, "std", "damage", 0)
        setWeaponProperty(28, "pro", "damage", 0)
        setWeaponProperty(28, "poor", "damage", 0)
------------------------------- remington 870
        setWeaponProperty(25, "poor", "flag_move_and_shoot", true)
        setWeaponProperty(25, "poor", "flag_move_and_aim", true)
        setWeaponProperty(25, "poor", "flag_aim_1st_person", false)
        setWeaponProperty(25, "poor", "flag_aim_no_auto", true)
        setWeaponProperty(25, "poor", "flag_anim_reload_long", false)
        setWeaponProperty(25, "poor", "anim_loop_stop", 1)
        setWeaponProperty(25, "poor", "anim2_loop_stop", 0.07)
        setWeaponProperty(25, "poor", "maximum_clip_ammo", 1)
        setWeaponProperty(25, "poor", "accuracy", 50)
        setWeaponProperty(25, "poor", "damage",10)
        setWeaponProperty(25, "std", "damage",10)
        setWeaponProperty(25, "pro", "damage",10)
        setWeaponProperty(25, "poor", "weapon_range", 15)
        setWeaponProperty(25, "std", "weapon_range", 15)
        setWeaponProperty(25, "pro", "weapon_range", 15)
end
)




----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------


