--setVehicleHandling ( element theVehicle, string property, var value )

-- Anthony Script -- 2015.09.21. 22:51
-- Felhasznált weboldal: http://gta.wikia.com/wiki/Handling.cfg/GTASA --
 
--alapcuccos--
--setVehicleHandling(veh, "mass", 2600)
--setVehicleHandling(veh, "turnMass", 6333.3)
--setVehicleHandling(veh, "dragCoeff",2.0)
--setVehicleHandling(veh, "centerOfMass", { 0.0, 0.0, -0.2})
--setVehicleHandling(veh, "percentSubmerged", 80)
--setVehicleHandling(veh, "tractionMultiplier", 0.95)
--setVehicleHandling(veh, "tractionLoss", 0.70)
--setVehicleHandling(veh, "tractionBias", 0.46)
--setVehicleHandling(veh, "numberOfGears", 5)
--setVehicleHandling(veh, "maxVelocity", 860)  -- végsebesség 
--setVehicleHandling(veh, "engineAcceleration", 15)   -- Gyorsulás 
--setVehicleHandling(veh, "engineInertia", 30)
--setVehicleHandling(veh, "driveType", "FWD")
--setVehicleHandling(veh, "engineType", "petrol")
--setVehicleHandling(veh, "brakeDeceleration", 3.0)   -- fékezés 
--setVehicleHandling(veh, "brakeBias", 0.80)
--setVehicleHandling(veh, "ABS", false)
--setVehicleHandling(veh, "steeringLock", 44.0)
--setVehicleHandling(veh, "suspensionForceLevel", 1.5)
--setVehicleHandling(veh, "suspensionDamping", 0.07)
--setVehicleHandling(veh, "suspensionHighSpeedDamping", 2.0)
--setVehicleHandling(veh, "suspensionUpperLimit", 0.20)
--setVehicleHandling(veh, "suspensionLowerLimit", -0.12)
--setVehicleHandling(veh, "suspensionFrontRearBias", 0.45)
--setVehicleHandling(veh, "suspensionAntiDiveMultiplier", 0.0)
--setVehicleHandling(veh, "seatOffsetDistance", 0.2) 
--setVehicleHandling(veh, "collisionDamageMultiplier", 0.43)
--setVehicleHandling(veh, "monetary", 20000)
--setVehicleHandling(veh, "modelFlags", 1)
--setVehicleHandling(veh, "handlingFlags", 1)
--setVehicleHandling(veh, "headLight", 0)
--setVehicleHandling(veh, "tailLight", 3)
--setVehicleHandling(veh, "animGroup", 13)
--alapcuccos

--[[carro mao inglesa 
setVehicleHandling(v, "modelFlags", 1000002)
setVehicleHandling(v, "handlingFlags", 1000002)
]]

--addEvent("UpdateHandling",true);

-- DIRTBIKE 500 195 5 0 0.05 -0.09 103 2 0.9 0.48 5 350 50 300 r p 14 0.5 false 35 0.85 0.15 0 0.15 -0.16 0.5 0 0 0.15 10000 1000000 0 1 1 7
function loadHandling(v)	
	if getElementModel(v) == 481 then -- bmx
		setVehicleHandling(v, "maxVelocity", 50)
		setVehicleHandling(v, "engineAcceleration", 10)
	end
	if getElementModel(v) == 509 then -- bike
		setVehicleHandling(v, "maxVelocity", 40)
		setVehicleHandling(v, "engineAcceleration", 10)
	end
	if getElementModel(v) == 510 then -- M-Bike
		setVehicleHandling(v, "maxVelocity", 60)
		setVehicleHandling(v, "engineAcceleration", 10)
	end
	if getElementModel(v) == 468 then -- bf 400
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 195)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.09 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 50)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.85)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.16)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 497 then
		setVehicleHandling(v, "collisionDamageMultiplier", 30.0)
	end
	if getElementModel(v) == 493 then
		setVehicleHandling(v, "collisionDamageMultiplier", 0)
	end
	if getElementModel(v) == 446 then
		setVehicleHandling(v, "collisionDamageMultiplier", 0)
	end
	if getElementModel(v) == 452 then
		setVehicleHandling(v, "collisionDamageMultiplier", 0)
	end
	if getElementModel(v) == 539 then
		setVehicleHandling(v, "collisionDamageMultiplier", 0)
	end
	if getElementModel(v) == 586 then -- sanchez
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 195)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.09 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.9)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.16)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 463 then -- deamon
		setVehicleHandling(v, "mass", 800)
		setVehicleHandling(v, "turnMass", 403.3)
		setVehicleHandling(v, "centerOfMass", { 0, 0.1, -0.45 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 4)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 45)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.65)
		setVehicleHandling(v, "suspensionDamping", 0.02)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.09)
		setVehicleHandling(v, "suspensionLowerLimit", -0.11)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 523 then -- policebike
		setVehicleHandling(v, "mass", 800)
		setVehicleHandling(v, "turnMass", 403.3)
		setVehicleHandling(v, "centerOfMass", { 0, 0.1, -0.45 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 2.5)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 4)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 55)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.65)
		setVehicleHandling(v, "suspensionDamping", 0.02)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.09)
		setVehicleHandling(v, "suspensionLowerLimit", -0.11)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 581 then -- bati
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 200)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.09 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 45)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.85)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.5)
	end
	if getElementModel(v) == 521 then -- akuma
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 200)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.09 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 47)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.85)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.5)
	end
	if getElementModel(v) == 461 then -- Carbon
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 200)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.09 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 38)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		setVehicleHandling(v, "suspensionForceLevel", 0.85)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.5)
	end
	if getElementModel(v) == 522 then -- Double
		setVehicleHandling(v, "mass", 500)
		setVehicleHandling(v, "turnMass", 200)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 103)
		setVehicleHandling(v, "tractionMultiplier", 2)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.48)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 52)
		setVehicleHandling(v, "engineInertia", 300)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.5)
		
		setVehicleHandling(v, "suspensionForceLevel", 0.85)
		setVehicleHandling(v, "suspensionDamping", 0.15)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.15)
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.5)
	end
	if getElementModel(v) == 503 then -- maserati granturismo
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 270)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 150)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock", false)
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.28)
		setVehicleHandling(v, "suspensionLowerLimit", -0.17)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 598 then -- charger police
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 275)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.03 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
	end
	if getElementModel(v) == 561 then -- charger medic
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 260)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 250)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.03 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
		setVehicleHandling(v, "handlingFlags", 0x00002000)
	end
	if getElementModel(v) == 516 then -- charger civilian
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 265)
		setVehicleHandling(v, "engineAcceleration", 38)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.03 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
	end
	if getElementModel(v) == 603 then -- jaguar f-type civilian
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.6)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 42)
		setVehicleHandling(v, "engineInertia", 70)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock", false)
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.30)
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 547 then -- lancer evo civilian
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 220)
		setVehicleHandling(v, "engineAcceleration", 25)
		setVehicleHandling(v, "engineInertia", 250)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.01 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.14)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 566 then -- audi s5
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 230)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 250)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.75)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.03 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.7 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 458 then -- audi rs6
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 224)
		setVehicleHandling(v, "engineAcceleration", 34)
		setVehicleHandling(v, "engineInertia", 250)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.65)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.03 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.7 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 451 then -- l aventador sv
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.7)
		setVehicleHandling(v, "tractionLoss", 1.9)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 310)
		setVehicleHandling(v, "engineAcceleration", 47)
		setVehicleHandling(v, "engineInertia", 160)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.95)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.75 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 411 then -- bugatti divo
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.7)
		setVehicleHandling(v, "tractionLoss", 1.9)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 370)
		setVehicleHandling(v, "engineAcceleration", 39.7)
		setVehicleHandling(v, "engineInertia", 160)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.95)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.55 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "ABS", true)
	end
	if getElementModel(v) == 541 then -- ferrari california
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 285)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.01)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 477 then -- mercedes
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.7)
		setVehicleHandling(v, "tractionLoss", 1.9)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 287)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 160)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.95)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.65 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 502 then -- bugatti chiron
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.6)
		setVehicleHandling(v, "tractionLoss", 1.9)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 375)
		setVehicleHandling(v, "engineAcceleration", 49)
		setVehicleHandling(v, "engineInertia", 160)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.95)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.55 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "ABS", true)
	end
	if getElementModel(v) == 562 then -- gt-r civilian
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.92)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 100)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.99)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 559 then -- gt-r skyline civilian
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tract475ionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 274)
		setVehicleHandling(v, "engineAcceleration", 27)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.9)
	
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.25)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x1000002)
    	setVehicleHandling(v, "handlingFlags", 0x1000002)
	end
	if getElementModel(v) == 596 then -- crown police 
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1.7)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 200)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 140)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 23)
		setVehicleHandling(v, "brakeBias", 2)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", false)
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.28)
		setVehicleHandling(v, "suspensionLowerLimit", -0.17)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
	end
	if getElementModel(v) == 597 then -- taurus police 
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 250)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 100)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 23)
		setVehicleHandling(v, "brakeBias", 2)
		setVehicleHandling(v, "steeringLock", false)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.28)
		setVehicleHandling(v, "suspensionLowerLimit", -0.17)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 585 then -- crown civilian 
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 200)
		setVehicleHandling(v, "engineAcceleration", 16)
		setVehicleHandling(v, "engineInertia", 140)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)
		setVehicleHandling(v, "steeringLock", false)
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.28)
		setVehicleHandling(v, "suspensionLowerLimit", -0.17)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 426 then -- Dodge Neon
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 200)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 140)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "ABS", true)

        setVehicleHandling(v, "steeringLock",  35.0 )
        setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.06)
        setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
        setVehicleHandling(v, "suspensionUpperLimit", 0.15 )
        setVehicleHandling(v, "suspensionLowerLimit", -0.16)
        setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
        setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
        setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 466 then -- plymount volare
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.7)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 120)
		setVehicleHandling(v, "engineAcceleration", 10)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 4.8)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 555 then -- dodge charger rt 69
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.37 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier",1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 220)
		setVehicleHandling(v, "engineAcceleration",30)
		setVehicleHandling(v, "engineInertia", 90)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.15)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 439 then -- plymount 'cuda
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.5 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier",1.2)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 200)
		setVehicleHandling(v, "engineAcceleration",25)
		setVehicleHandling(v, "engineInertia", 90)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.35)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 400 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.6 } )
		setVehicleHandling(v, "tractionMultiplier", 0.8)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 200)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 250)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 490 then -- durango police
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.8)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 300)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 160)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 22)
		setVehicleHandling(v, "brakeBias", 2)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 492 then -- honda civic
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.8)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 180)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 185)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.01 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.16)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 546 then -- Honda Acord
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.5 } )
		setVehicleHandling(v, "tractionMultiplier", 0.8)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 180)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 190)
		setVehicleHandling(v, "driveType", "fwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.01 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 479 then -- GRAND CHEROKEE 4X4
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 260)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 260)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.1 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
	end
	if getElementModel(v) == 494 then -- BMW i8
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 1)
		setVehicleHandling(v, "maxVelocity", 223)
		setVehicleHandling(v, "engineAcceleration", 27)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 12)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 558 then -- mazda rx7
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 230)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 100)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 15)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.5)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x1000002)
	end
	if getElementModel(v) == 587 then -- 370z
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 230)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 15)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.7)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
	end
	if getElementModel(v) == 602 then -- camaro
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 223)
		setVehicleHandling(v, "engineAcceleration", 27)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 565 then -- brioso
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 180)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.8)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 527 then -- ford mustang gt
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 250)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.55)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
		setVehicleHandling(v, "handlingFlags", 0x00002000)
	end
	if getElementModel(v) == 415 then -- supra
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 275)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x1000002)
		setVehicleHandling(v, "handlingFlags", 0x1000002)
	end
	if getElementModel(v) == 445 then -- M5 E60
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 223)
		setVehicleHandling(v, "engineAcceleration", 27)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 506 then -- corvette
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 0.9 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 260)
		setVehicleHandling(v, "engineAcceleration", 37)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)
		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.45)
		setVehicleHandling(v, "suspensionDamping", 0.1 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
	if getElementModel(v) == 475 then -- dodge challenger
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.4 } )
		setVehicleHandling(v, "tractionMultiplier", 1.1 )
		setVehicleHandling(v, "tractionLoss", 1.7 )
		setVehicleHandling(v, "tractionBias", 0.5)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 301)
		setVehicleHandling(v, "engineAcceleration", 37.5)
		setVehicleHandling(v, "engineInertia", 120)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9.5)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.1 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.15)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.52 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
		setVehicleHandling(v, "modelFlags", 0x00002000)
		setVehicleHandling(v, "handlingFlags", 0x00002000)
	end
	if getElementModel(v) == 579 then -- silverado
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 4500)
		setVehicleHandling(v, "centerOfMass", { 0, 0.4, -0.6 } )
		setVehicleHandling(v, "tractionMultiplier", 0.8)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.52)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 160)
		setVehicleHandling(v, "engineAcceleration", 23)
		setVehicleHandling(v, "engineInertia", 130)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 8)
		setVehicleHandling(v, "brakeBias", 0.9)

		setVehicleHandling(v, "steeringLock",  35.0 )
		setVehicleHandling(v, "suspensionForceLevel", 0.6)
		setVehicleHandling(v, "suspensionDamping", 0.08 )
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.1 )
		setVehicleHandling(v, "suspensionLowerLimit", -0.2)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.6 )
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.0)
		setVehicleHandling(v, "seatOffsetDistance", 0.0)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.55)
	end
end

function loadHandlings()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

function vehicleEnter()
	loadHandling(source)
end
addEventHandler("onVehicleEnter", getRootElement(), vehicleEnter)

function reloadHandlings(veh)
	if veh then
		loadHandling(veh)
	end
end
addEvent("reloadHandlings",true)
addEventHandler ( "reloadHandlings", getRootElement(), reloadHandlings )


function startdrifmode(v)
	if v then
		setVehicleHandling(v, "mass", 1000 )
		setVehicleHandling(v, "turnMass", 3000 )
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.65 } )
		setVehicleHandling(v, "tractionMultiplier", 0.55)
		setVehicleHandling(v, "tractionLoss", 0.65)
		setVehicleHandling(v, "tractionBias", 0.45 )
		setVehicleHandling(v, "numberOfGears", 1)
		setVehicleHandling(v, "maxVelocity", 135)
		setVehicleHandling(v, "engineAcceleration", 156 )
		setVehicleHandling(v, "steeringLock",  66.0 )
		setVehicleHandling(v, "engineInertia", 100)
		setVehicleHandling(v, "driveType", "rwd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 9)
		setVehicleHandling(v, "brakeBias", 0.9)
	end
end
addEvent("startdrifmode",true)
addEventHandler ( "startdrifmode", getRootElement(), startdrifmode )